### ISSUE TITLE
_Grid.CSHTML exception

### ISSUE THREAD

**Issue by mkchmiel** [NonFactors/MVC5.Grid#116]
Been a while since I worked on this, not sure if this is a bug or a mistake somewhere on my part but I am getting an exception. Any ideas what could cause this?
```
System.InvalidOperationException
  HResult=0x80131509
  Message=The model item passed into the dictionary is of type
NonFactors.Mvc.Grid.Grid`1[RBGCustomPortal.Models.LBILocation]', but this dictionary requires a model item of type 'System.Collections.Generic.IEnumerable`1[RBGCustomPortal.Models.LBILocation]'.
  Source=System.Web.Mvc
  StackTrace:
   at System.Web.Mvc.ViewDataDictionary`1.SetModel(Object value)
   at System.Web.Mvc.ViewDataDictionary..ctor(ViewDataDictionary dictionary)
   at System.Web.Mvc.WebViewPage`1.SetViewData(ViewDataDictionary viewData)
   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)
   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.HtmlHelper.RenderPartialInternal(String partialViewName, ViewDataDictionary viewData, Object model, TextWriter writer, ViewEngineCollection viewEngineCollection)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model)
   at ASP._Page_Views_Shared_MvcGrid__Grid_cshtml.Execute() in e:\Solutions\Web\RBGCustomPortal\RBGCustomPortal\Views\Shared\MvcGrid\_Grid.cshtml:line 73
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)
   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.HtmlHelper.RenderPartialInternal(String partialViewName, ViewDataDictionary viewData, Object model, TextWriter writer, ViewEngineCollection viewEngineCollection)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at NonFactors.Mvc.Grid.HtmlGrid`1.ToHtmlString()
   at System.Web.WebPages.WebPageBase.Write(Object value)
   at ASP._Page_Views_LBI_Partials__LocationGrid_cshtml.Execute() in e:\Solutions\Web\RBGCustomPortal\RBGCustomPortal\Views\LBI\Partials\_LocationGrid.cshtml:line 5
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)
   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
```
I have this working else where and the only difference I found is that one uses entity framework and the broken on is using List<Model> which is passed as enumerable. I have played around a bit with this and haven't identified what could have caused this.

**Comment by Muchiachio** [comment]
Do you pass an enumerable as a grid source? In `Html.Grid(<here>)`.

**Comment by mkchmiel** [comment]
Yeah i handle it like this: List<Model>().AsEnumerable(),
I cannot think of any reason why this wouldn't work.

![image](https://user-images.githubusercontent.com/1263432/35642343-7b1ec1ae-0688-11e8-9c9a-aa8d162bf638.png)

**Comment by Muchiachio** [comment]
Actually, I see that you are using a footer view, does it take `IGrid<LBILocation>` as it's model?

**Comment by mkchmiel** [comment]
Yup
![image](https://user-images.githubusercontent.com/1263432/35643159-0bacb544-068b-11e8-9e0b-c3ce5bbf9bc8.png)

**Comment by mkchmiel** [comment]
Are there any work around to the footer view? I had one but it was ugly and required additional javascript on the pages.

**Comment by Muchiachio** [comment]
No it's ok like that, I'm just not sure where the problem is, would you mind creating a repro?
Because, I can't reproduce.

**Comment by mkchmiel** [comment]
I dont think I would be able to since all the data read is only available locally so I am not sure how you would be able to test it remotely?

Anyway for me to find where the legit error is being caused? I tried with f11 but I just find myself suddenly on the _grid.cshtml page with an error.

**Comment by mkchmiel** [comment]
I just tried passing in a empty list and it seems to throw the same kind of error:

return PartialView("Partials/_LocationGrid", new List<RBGCustomPortal.Models.LBILocation>().AsEnumerable());

**Comment by mkchmiel** [comment]
As soon as I remove the .WithFooter("Partials/_LocationGrid") it doesnt throw an error but of course the footer wont show.

**Comment by mkchmiel** [comment]
Found my bug, lets close this out.
